languague: go
install:
- go get -v github.com/CascaraTest/hugosite
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: DhA8wkED+cFYbSW8u8daP0BuJfQxzrcX3YDu2vY8WeMzOHdvIN9mBr3yZ56qkSnlRhtmlP/1SfzvIb+Ulw/eGqgLZa3ks2ZZyB131ol1IBc9ozuuzAAL0J8foZhcxJkj2m3zrAqlbe7U31CG3d0duUg0C9Qq0awlG3PqbsTNx8fx/oDauPZyZG1t89CmatCb6tmCOLGdE4a/db7TCLTBfk+3iHBll/vuSL8yfNET3C9kUONZe4hWREh9Cyt7Knrq50ahc5mWYIUIfOfHrYsA+gAnyLJZGHVprKqSGQu0wMlNr2r37YxXhZEwsDNIcjxrmfH3353CVMCm9pSb8At6uPw43X5xPpL6IHKzo5a6pxI3mlqxD9t5QonV1wh2aDsun73D56BRFZbiXDTTUmzku6VD1sWFoyi49iUemQE8nOhpuKxO5LE4BFJ5aqnBOgbM8K7kIf9LKYAbh3fY+va46O7vPvoQ9NzhTv0t0U+obWTIJqQGE9CAZh3fqRCYpzlF4OQzFiaZ/UnxL+3QwRdCLfrn0jO4ryJgdtkQmpwH+ANHE392xScO11022I0+DEaBL5oViwZPyubBUwHrVolZACcEKbnbCAt0hDAqvz+Fm8xdH/et8yN0V4KNVJc3uJ2yIv9RwOzvWDRa6Wfh9+9OBmfaeP8C+DtdJS9NVi2sak8=
  - secure: uLPaMPjTuPp1cnc0i1CNKqr/1fTPYUhDzrjIFhUxVoXyyPUpX1E6VHYBoBWWkqNgPWjYRc736V8m652tBY6SRypG/6e+0ANi8MbimdKFUPJDYOcM2JeTqeX/UquNtMRm43OTm+UAl8xLWgBCvStxUHsY8rrxKZLFlO2+WZXlSfeiZWf9RoCgYv9abhWjbQQXz7Yi+XSVT2mDKFLxIEhKKMfKT+nQrMUkTe8GgLhCPGw36wmtGbOSvNwCh0BydIw7limFhRrzEvQhMaCB0wNn2IlL0BmK437467hOSsOCFDXevkU8HsSUpbtIXluynf5nbzWiTIkoaeO8eEjAbwkbTiI+uLdyWdpDiy0wCqKOxtxshoRhWzB2lZc95qX1u0VTBFzKpJOuVtrXVXc7LLspB6sZ1XavGnEGPxuma9L7+4y79uGIO85hpMuNrw0SI+iZhy+//UWl+MnQ52FLNHdo0ZBKuleG8oXAXYZHYojQLhXFLDzqV+dFnJNXGCLOKoX1muLWY0U/IEnOZvNsXoE4aoy3ZQ1ajwCR0U1/LFSxab7xQRcuKduHiKzTtY6KpRYrvU20PpGRz1BW2WnizWlXfZLLCY5RVvexprva6XAK3uahqm+bpkS/07Mmq+2tjKikjMOLnd5721Xd/takyS+Tc7LNdAaYFYT4TtqbXwmBL2c=
