languague: go
install:
- go get -v github.com/CascaraTest/hugosite
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: VIKxOZeUdKA3/0vJlpvCTD3fBxNF1cWbBHJ43OEhgL9VgwnGvFVQC/qcBtOyFHYW5iMtezzkLE8Joc4h1QGbKCUz5Pwrbg2PjlOwJtRHfhjnrVWHhtRG+amgM+4iULYhb6ogskMAcKGNBdvDTDTPECnBB04apN6b96+909kdJCfu0+kiBEN1uclAR71sgBDqWgU23u7qsAU7yF2qBqdZwJ0KPw5CGRgLCZCtB2pYYItCG5LcnAv+ixgjWgVg7vB2zY02EwcGlaXuNeNG9bQqIoJYJu28AFrk98Wbh4ERe/DFAtnmQSJBKoK2lJoqJZzAVI7wSrxv12lUehMxWLeCMJoIkUHAeQ8gA8hZcGbGIWUhZx27GYKOLtWM3jF49vsVE8vH34MKnRLVZnyGAHwfmlgNeJOjDMisTnnxPgWrvQFrHZ+WELe7NtJJ9H5QDslQpMXFjN0DQCTR10IrA3Rf6S9EN0ZxQ3lIsvf7qk/EOc7RECfLb2KSIVxE8Zivb8/qi/pbKJ5d9MPOSKHwRPtLJ5tMAnXma2x4CNoyTIO0nCrrZrSISPSaGECK5873XMkBjRv7yGmRHWoya7u2Z3S1iCyg/DU7YbhEXTkEkC2KmHebhKepa49YaNGP/chJFUn72EOPLgeozqSErrf6hSku/r3CHdazs/imgOLFLXWPAD0=
  - secure: VAvucynrLTYjC5W/BiLQve2yIFYYKmF6/udtkoYtD+LVbZFrjj0h9BpMjuz4jtoJrFg/ACodONf6516eGpdLlO7IBpDwamkPHFH82kQWAJrXLRFZdqYprBCcr0XcLXHrmfQFhJ5lWcvnGge+Cedo59k1dGwRJ67I5crovdAHrJnxSufqhr7tIqqlDXyuKqwB+xK1IXW6/1ZiGFJoXSAzbBtWdVoe4SiCDZlzfI+bg6aueFSf7IARl6uXMdy72Vw20WFil55mnFsigL9ybwzwmXTRU5vzIjMm1Z4f/NQ5xB8epCXONmOhGS6mVYfhZsxYzf3eZ7BcTK7SBJQEIiHt3JZG1KrvArIWYIYLmcbSxM2tPfQpvZHqtdo5FXuJouBLl7CFbEI25JnCO3aSlDQDCFC4EOKkW4C6JJKgY8wJ6Kf7WB+nInb3/FoEVWV94Qiu37r/Jnb5tmJMjRjq6BwcXSE/SG+jryrV52ptATPxmIQCi1UrYq2ozRAUGD+v70zsLPx7ItJhiFLc4HKJR2B3bWFj5xdB0YbwK28oAgGUpmH94as9OUQYI7QIk9wWjDT/2gQz0N725XDm1+Y8drhfIf+TwA7ZGq7OUkKeHk2ilL2CGvdEUVYc8pPcO7pprrdeSwDNnaLfsWqyPPUJMVYbldNUxfBG/56fUuF8s4O6XoM=
